/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#303221",
        "on-tertiary-fixed-variant": "#3c475b",
        "error": "#ffb4ab",
        "secondary": "#c8c8b0",
        "on-tertiary-container": "#364155",
        "secondary-container": "#494a38",
        "inverse-on-surface": "#313030",
        "surface-container-low": "#1c1b1b",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "primary": "#e5c483",
        "inverse-primary": "#735b24",
        "on-secondary-fixed": "#1b1d0e",
        "on-primary-fixed": "#261a00",
        "tertiary-fixed-dim": "#bbc7df",
        "primary-fixed-dim": "#e3c281",
        "surface-container": "#201f1f",
        "tertiary-fixed": "#d7e3fc",
        "on-primary": "#402d00",
        "on-tertiary-fixed": "#101c2e",
        "tertiary-container": "#a2adc5",
        "tertiary": "#bdc8e1",
        "on-surface-variant": "#d0c5b5",
        "on-primary-container": "#533d07",
        "primary-container": "#c8a96a",
        "secondary-fixed": "#e4e4cc",
        "on-error-container": "#ffdad6",
        "outline-variant": "#4d463a",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#253144",
        "inverse-surface": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "error-container": "#93000a",
        "primary-fixed": "#ffdf9f",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353534",
        "secondary-fixed-dim": "#c8c8b0",
        "on-secondary-fixed-variant": "#474836",
        "on-primary-fixed-variant": "#5a430e",
        "surface-container-highest": "#353534",
        "background": "#131313",
        "surface-tint": "#e3c281",
        "on-secondary-container": "#b9baa3",
        "outline": "#998f81",
        "surface": "#131313",
        "surface-bright": "#393939"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
